"use client"

import { useEffect, useState } from "react"
import { AppDrawer } from "@/components/ui/AppDrawer"
import { Button } from "@/components/ui/Button"
import { formatEuro } from "@/lib/formatters"
import { getOrCreateCommercialQuoteAction, saveCommercialQuoteAction } from "@/features/financial-modeling/actions"
import type { CommercialQuote } from "@/features/financial-modeling/data/commercial-quote"

type Props = { modelId: string; open: boolean; onOpenChange: (open: boolean) => void }
const inputClass = "mt-1 w-full rounded-md border border-border bg-canvas px-3 py-2.5 text-sm text-heading"

export function CommercialQuoteMobileDrawer({ modelId, open, onOpenChange }: Props) {
  const [quote, setQuote] = useState<CommercialQuote | null>(null); const [loading, setLoading] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  useEffect(() => { if (!open) return; setLoading(true); void getOrCreateCommercialQuoteAction(modelId).then((result) => { if ("error" in result) setError(result.error ?? "Impossible de préparer le devis"); else setQuote(result.quote); setLoading(false) }) }, [modelId, open])
  const update = <K extends keyof CommercialQuote>(key: K, value: CommercialQuote[K]) => setQuote((current) => current ? { ...current, [key]: value } : current)
  const save = async () => { if (!quote) return; setSaving(true); const result = await saveCommercialQuoteAction(quote); if ("error" in result) setError(result.error ?? "Impossible d’enregistrer le devis"); setSaving(false) }
  return <AppDrawer open={open} onOpenChange={onOpenChange} side="bottom" title="Devis client" className="sm:hidden h-[90vh]" footer={<><Button variant="secondary" size="md" className="min-h-11 flex-1" onClick={() => onOpenChange(false)}>Fermer</Button><Button variant="primary" size="md" className="min-h-11 flex-1" loading={saving} disabled={!quote} onClick={save}>Enregistrer</Button></>}>
    {loading ? <p className="py-10 text-center text-sm text-muted">Préparation du devis…</p> : error ? <p className="text-sm text-danger">{error}</p> : quote ? <div className="space-y-4"><label className="block text-xs font-bold text-muted">Titre<input className={inputClass} value={quote.title} onChange={(e) => update("title", e.target.value)} /></label><label className="block text-xs font-bold text-muted">Objet<input className={inputClass} value={quote.subject} onChange={(e) => update("subject", e.target.value)} /></label><div className="grid grid-cols-2 gap-3"><label className="text-xs font-bold text-muted">Début<input type="date" className={inputClass} value={quote.startDate} onChange={(e) => update("startDate", e.target.value)} /></label><label className="text-xs font-bold text-muted">Fin<input type="date" className={inputClass} value={quote.endDate ?? ""} onChange={(e) => update("endDate", e.target.value || null)} /></label><label className="text-xs font-bold text-muted">Jours<input type="number" className={inputClass} value={quote.productionDays} onChange={(e) => update("productionDays", Number(e.target.value))} /></label><label className="text-xs font-bold text-muted">TJM<input type="number" className={inputClass} value={quote.dailyRate} onChange={(e) => update("dailyRate", Number(e.target.value))} /></label></div><label className="block text-xs font-bold text-muted">Montant HT<input type="number" className={inputClass} value={quote.totalExcludingTax} onChange={(e) => update("totalExcludingTax", Number(e.target.value))} /></label><label className="block text-xs font-bold text-muted">Conditions<textarea className={inputClass} value={quote.conditions} onChange={(e) => update("conditions", e.target.value)} /></label><label className="block text-xs font-bold text-muted">Notes<textarea className={inputClass} value={quote.notes} onChange={(e) => update("notes", e.target.value)} /></label><details className="border-t border-border pt-4"><summary className="cursor-pointer text-xs font-bold text-heading">Aperçu du devis</summary><div className="mt-3 text-sm"><p className="font-bold">{quote.resource}</p><p>{quote.profile}</p><p className="mt-3">{quote.productionDays} jours × {formatEuro(quote.dailyRate)}</p><p className="font-mono text-lg font-bold">{formatEuro(quote.totalExcludingTax)} HT</p><Button type="button" variant="secondary" size="md" className="mt-4 min-h-11 w-full" onClick={() => window.print()}>Imprimer / Enregistrer en PDF</Button></div></details></div> : null}
  </AppDrawer>
}
