import { describe, expect, it } from "vitest"
import type { BuildEngagementsPortfolioInput, PortfolioMissionSource, PortfolioProjectSource } from "../engagements-portfolio-types"
import { buildClientExposure, buildMarginBridge, buildPortfolioPoints, buildProductionHeatmap, buildProjectsCockpit, buildRunway } from "../engagements-portfolio-utils"

const NOW = new Date("2026-07-17T10:00:00Z")
const mission = (id = "m1", companyId = "c1"): PortfolioMissionSource => ({ id, title: `Mission ${id}`, startDate: "2026-01-01", endDate: "2026-07-10", practice: "Data & IA", companyId, companyName: `Client ${companyId}`, collaboratorId: `collab-${id}`, grossMarginPct: 35 })
const project = (id = "p1", companyId = "c2"): PortfolioProjectSource => ({ id, title: `Projet ${id}`, startDate: "2026-02-01", endDate: "2026-10-01", companyId, companyName: `Client ${companyId}`, practice: "Cloud", progressPct: 50, contractAmount: 100_000, costActual: 20_000, actualMarginPct: 18, targetMarginPct: 30, billingMilestones: [{ label: "Facture", amount: 30_000, dueDate: "2026-06-01", invoicedAt: "2026-06-02" }] })
const input = (overrides: Partial<BuildEngagementsPortfolioInput> = {}): BuildEngagementsPortfolioInput => ({ now: NOW, missions: [mission()], projects: [project()], reports: [{ id: "r1", missionId: "m1", collaboratorId: "collab-m1", status: "validated", periodStart: "2026-06-01", periodEnd: "2026-06-30", billableDays: 10, businessDays: 20, tjmSnapshot: 800, cjmSnapshot: 500 }], collaborators: [], compensations: [{ collaboratorId: "collab-m1", taci: .8, effectiveFrom: "2026-01-01", effectiveTo: null }], projectPhases: [], projectTeamMembers: [], calendarEvents: [], ...overrides })

describe("portfolio engagement calculations", () => {
  it("calculates AT margin from validated snapshots and ignores future or unvalidated CRA", () => { const points = buildPortfolioPoints(input({ reports: [...input().reports, { ...input().reports[0], id: "future", periodStart: "2026-08-01", periodEnd: "2026-08-31", tjmSnapshot: 10_000, cjmSnapshot: 0 }, { ...input().reports[0], id: "draft", status: "submitted", tjmSnapshot: 10_000, cjmSnapshot: 0 }] })); expect(points[0]).toEqual(expect.objectContaining({ revenueYtd: 8_000, actualMarginPct: 37.5, marginGapPct: 2.5, overdue: true, daysUntilEnd: -7 })) })
  it("uses project actual_margin_pct and keeps a missing end date", () => { const points = buildPortfolioPoints(input({ missions: [], reports: [], projects: [{ ...project(), endDate: null }] })); expect(points[0]).toEqual(expect.objectContaining({ actualMarginPct: 18, marginGapPct: -12, daysUntilEnd: null, overdue: false, revenueYtd: 30_000 })) })
  it("calculates client concentration and AT/project split", () => { const points = buildPortfolioPoints(input({ projects: [{ ...project(), companyId: "c1", companyName: "Client c1" }] })); const result = buildClientExposure([...points, { ...points[1], id: "p2", companyId: "c2", companyName: "Client c2", revenueYtd: 4_000 }]); expect(result.concentration).toEqual({ firstClientPct: 90.5, top3ClientsPct: 100 }); expect(result.clients[0]).toEqual(expect.objectContaining({ assistanceRevenue: 8_000, projectRevenue: 30_000 })) })
  it("builds monthly heatmaps and groups the long tail under Autres", () => { const missions = Array.from({ length: 9 }, (_, index) => mission(`m${index}`, `c${index}`)); const reports = missions.map((item, index) => ({ ...input().reports[0], id: `r${index}`, missionId: item.id, collaboratorId: item.collaboratorId })); const result = buildProductionHeatmap(input({ missions, projects: [], reports })); expect(result.clients).toHaveLength(8); expect(result.clients.at(-1)?.label).toBe("Autres"); expect(result.clients[0].monthly[5].revenue).toBe(8_000) })
  it("counts only invoiced milestones, remaining amount and overdue phases", () => { const result = buildProjectsCockpit(input({ projects: [{ ...project(), billingMilestones: [...project().billingMilestones, { label: "Non facturé", amount: 20_000, dueDate: "2026-07-01", invoicedAt: null }] }], projectPhases: [{ id: "phase", projectId: "p1", label: "Cadrage", status: "in_progress", startDate: "2026-05-01", endDate: "2026-07-01" }] })); expect(result[0]).toEqual(expect.objectContaining({ invoicedAmount: 30_000, remainingToInvoice: 70_000 })); expect(result[0].phaseCounts.overdue).toBe(1) })
  it("builds AT margin and project contribution bridges", () => { const result = buildMarginBridge(input()); expect(result.assistanceTechnique).toEqual({ revenue: 8_000, assistanceCosts: 5_000, projectCosts: 0, observedContribution: 3_000 }); expect(result.projects.observedContribution).toBe(10_000); expect(result.global.observedContribution).toBe(13_000) })
  it("deduplicates equivalent runway markers", () => { const result = buildRunway(input({ projectPhases: [{ id: "phase", projectId: "p1", label: "Livraison", status: "planned", startDate: null, endDate: "2026-08-01" }], calendarEvents: [{ id: "event", entityType: "project", entityId: "p1", title: "Livraison", eventType: "delivery", status: "scheduled", startsAt: "2026-08-01T09:00:00Z" }] })); expect(result.find((row) => row.id === "p1")?.markers.filter((marker) => marker.label === "Livraison")).toHaveLength(1) })
})
