-- Source fidèle : arkopharma/arkopharma_audit_strategique_process.pdf, sections 2 à 4.
DO $$
DECLARE v_company_id uuid; v_payload jsonb;
BEGIN
  SELECT id INTO v_company_id FROM public.companies WHERE name ILIKE '%arkopharma%' LIMIT 1;
  IF v_company_id IS NULL THEN RAISE EXCEPTION 'Arkopharma introuvable'; END IF;
  v_payload := $json${
    "companyId":"__COMPANY_ID__","title":"Audit Stratégique Arkopharma — Optimisation des Processus Opérationnels","auditDate":"2026-06-01",
    "operationalActivities":[
      {"domain":"R&D et Innovation Produit","introduction":"La R&D d'Arkopharma mobilise environ 8,5 % de l'effectif (≈ 103 personnes), couvrant la formulation galénique, les études cliniques, la veille scientifique et l'innovation produit.","activities":[{"code":"RD1","label":"Veille scientifique et tendances","description":"Analyse des publications, brevets, tendances marché. Identification des actifs et formulations innovantes. Benchmark concurrentiel.","workload":"10-15 %"}]},
      {"domain":"Affaires Réglementaires et Pharmacovigilance","introduction":"Fonction critique chez un laboratoire pharmaceutique, les affaires réglementaires garantissent la conformité de chaque produit dans chaque marché.","activities":[{"code":"AR1","label":"Veille réglementaire multi-pays","description":"Suivi des évolutions réglementaires (CE 1924/2006, PPWR, Farm to Fork, listes positives) dans 65+ pays. Anticipation des impacts produits.","workload":"15-20 %"}]},
      {"domain":"Production Industrielle et Qualité","introduction":"Arkopharma exploite trois sites de production (Carros, Waterford, Vintimille) avec une centaine de machines et lignes de production.","activities":[{"code":"PR1","label":"Planification de production","description":"Ordonnancement des OF, gestion des priorités saisonnières, équilibrage des lignes multi-formats (gélules, comprimés, gummies, liquides).","workload":"15-20 %"}]},
      {"domain":"Supply Chain et Achats","activities":[{"code":"SC1","label":"Sourcing et achats MP végétales","description":"Identification et qualification des filières de plantes et actifs naturels. Négociation des contrats, certification bio/durable.","workload":"25-30 %"}]},
      {"domain":"Commercial et Force de Vente Officinale","activities":[{"code":"CO1","label":"Visite pharmaceutique terrain","description":"Visites des pharmacies pour présenter les nouveautés, former les équipes officinales, négocier le référencement et le facing.","workload":"30-35 %"}]},
      {"domain":"Marketing, Communication et Digital","activities":[{"code":"MK1","label":"Stratégie de marque et positionnement","description":"Gestion du portefeuille de marques (Arkogélules, Forcapil, Phytosun Arôms, etc.). Positionnement et architecture de marque.","workload":"10-15 %"}]},
      {"domain":"Direction Administrative et Financière","activities":[{"code":"DA1","label":"Comptabilité et clôtures","description":"Comptabilité générale et auxiliaire. Clôtures mensuelles/trimestrielles. Consolidation groupe et remontées Dermapharm.","workload":"25-30 %"}]},
      {"domain":"Ressources Humaines et Fonctions Support","activities":[{"code":"RH1","label":"Recrutement et intégration","description":"Sourcing de profils spécialisés (pharmaciens, formulateurs, analytistes, délégués pharma). Onboarding.","workload":"20-25 %"}]}
    ],
    "stakeholders":[
      {"domain":"R&D et Innovation","stakeholders":[{"name":"Affaires réglementaires (interne)","frequency":"Quotidien","nature":"Validation allégations, dossiers AMM, conformité formules","friction":"Goulot réglementaire sur chaque formule"}]},
      {"domain":"Commercial et Force de Vente","stakeholders":[{"name":"Pharmaciens d'officine","frequency":"Quotidien","nature":"Référencement, formation, merchandising, promotions","friction":"Temps limité en officine, concurrence des délégués"}]},
      {"domain":"Production et Supply Chain","stakeholders":[{"name":"Fournisseurs MP végétales","frequency":"Quotidien","nature":"Commandes, réception, qualité, certificats","friction":"Volatilité prix, aléas climatiques sur les récoltes"}]},
      {"domain":"Marketing et Digital","stakeholders":[{"name":"Agences créatives / médias","frequency":"Hebdomadaire","nature":"Campagnes publicitaires, podcast, influence, production contenu","friction":"Allers-retours validation réglementaire des communications"}]}
    ],
    "workload":{"columns":["Fonction","Cœur de métier","Qualité / Conformité","Coordination","Pilotage"],"rows":[{"domain":"R&D / Innovation","values":["Formulation & études (45 %)","Dossiers réglementaires (25 %)","Veille & innovation (15 %)","Industrialisation (15 %)"]},{"domain":"Affaires réglementaires","values":["Dossiers AMM (35 %)","Allégations & conformité (30 %)","Coordination multi-pays (20 %)","Veille réglementaire (15 %)"]},{"domain":"Production / Qualité","values":["Fabrication (40 %)","Contrôle qualité / BPF (20 %)","Planification (20 %)","Maintenance / HSE (20 %)"]},{"domain":"Supply Chain","values":["Approvisionnement (30 %)","Qualité fournisseurs (15 %)","Logistique / stocks (30 %)","S&OP / prévisions (25 %)"]},{"domain":"Commercial","values":["Visite officinale (35 %)","Admin des ventes (15 %)","CRM / reporting (25 %)","Comptes clés (25 %)"]},{"domain":"Marketing / Digital","values":["Marque & produit (35 %)","Conformité communications (10 %)","Création contenu (30 %)","E-commerce / analytics (25 %)"]},{"domain":"DAF","values":["Comptabilité / clôture (30 %)","Contrôle de gestion (25 %)","Fiscalité / compliance (25 %)","Trésorerie (20 %)"]},{"domain":"RH / Support","values":["Recrutement / paie (45 %)","Formation réglementaire (20 %)","DSI / IT (25 %)","Services généraux (10 %)"]}],"keyInsight":"Constat clé : La charge réglementaire et de conformité représente 15 à 30 % du temps dans quasiment toutes les fonctions — jusqu'à 55 % pour les affaires réglementaires pures. C'est le premier poste d'optimisation. L'IA documentaire (extraction, classification, génération de fiches réglementaires, vérification automatique des allégations) peut réduire cette charge de 40 à 60 % tout en améliorant la fiabilité et la traçabilité."}
  }$json$::jsonb;
  v_payload := jsonb_set(v_payload, '{companyId}', to_jsonb(v_company_id::text));
  UPDATE public.ai_intelligence_results SET content_json = jsonb_set(content_json, '{cartographies}', v_payload, true) WHERE company_id = v_company_id AND result_type = 'process_diagnostic' AND status = 'succeeded';
END $$;
